CREATE SEQUENCE DEPT_ID_9999999
    INCREMENT BY 10
    START WITH 60
    MAXVALUE 500
    NOCYCLE
    NOCACHE;

SELECT
    SEQUENCE_NAME, MIN_VALUE,
    MAX_VALUE, INCREMENT_BY,
    LAST_NUMBER
    FROM USER_SEQUENCES WHERE SEQUENCE_NAME='DEPT_ID_9999999';

ALTER SEQUENCE DEPT_ID_9999999
    INCREMENT BY 5
    MAXVALUE 600
    NOCACHE
    NOCYCLE;

SELECT
    SEQUENCE_NAME, MIN_VALUE,
    MAX_VALUE, INCREMENT_BY,
    LAST_NUMBER
    FROM USER_SEQUENCES WHERE SEQUENCE_NAME='DEPT_ID_9999999';

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
    VALUES
    (DEPT_ID_9999999.NEXTVAL, 'HR', 'ITALY');

SELECT DEPT_ID_9999999.CURRVAL
    FROM DUAL;

SELECT * FROM DEPT;

CREATE INDEX DEPT_IDX_99999999
    ON DEPT(DEPTNO, DNAME);

SELECT ic.INDEX_NAME, ic.TABLE_NAME, ic.COLUMN_NAME
    FROM USER_IND_COLUMNS ic
    WHERE ic.INDEX_NAME='DEPT_IDX_99999999';


