CREATE TABLE PEGAWAI_NAMALO(
    ID_Pegawai VARCHAR2(10) NOT NULL,
    Nama_Pegawai VARCHAR2(10) NOT NULL,
    Jabatan VARCHAR2(20) NOT NULL
);

INSERT INTO PEGAWAI_NAMALO (ID_Pegawai, Nama_Pegawai, Jabatan) VALUES ('PEG001', 'Ayunda', 'Manager');
INSERT INTO PEGAWAI_NAMALO (ID_Pegawai, Nama_Pegawai, Jabatan) VALUES ('PEG002', 'Doni', 'HRD');
INSERT INTO PEGAWAI_NAMALO (ID_Pegawai, Nama_Pegawai, Jabatan) VALUES ('PEG003', 'Hani', 'Marketing');
INSERT INTO PEGAWAI_NAMALO (ID_Pegawai, Nama_Pegawai, Jabatan) VALUES ('PEG004', 'Lukman', 'Office Boy');
INSERT INTO PEGAWAI_NAMALO (ID_Pegawai, Nama_Pegawai, Jabatan) VALUES ('PEG005', 'Putri', 'Kreatif');

SELECT * FROM PEGAWAI_NAMALO;

ALTER TABLE PEGAWAI_NAMALO ADD Gaji VARCHAR2(25);
ALTER TABLE PEGAWAI_NAMALO ADD Keterangan VARCHAR2(50);
DESC PEGAWAI_NAMALO;


ALTER TABLE PEGAWAI_NAMALO ADD DROP COLUMN Keterangan;
DESC PEGAWAI_NAMALO;

RENAME PEGAWAI_NAMALO TO KARYAWAN_LO;

ALTER TABLE KARYAWAN_LO MODIFY Gaji NUMBER(15);

TRUNCATE TABLE KARYAWAN_LO;

DROP TABLE KARYAWAN_LO;