CREATE TABLE MAHASISWA_123456
(NPM VARCHAR2(30), NAMA VARCHAR2(30), JURUSAN VARCHAR2(30));

INSERT INTO MAHASISWA_123456 VALUES(5315315, 'Turu', 'Teknik Informatika');
INSERT INTO MAHASISWA_123456 VALUES(53515134, 'Kau', 'Teknik Informatika');
INSERT INTO MAHASISWA_123456 VALUES(53534312, 'Deck', 'Teknik Informatika');

SELECT * FROM MAHASISWA_123456;


-- NO 1 ACT
SET SERVEROUTPUT ON
DECLARE
    V_NPM MAHASISWA_123456.NPM%TYPE := '5315315';
    V_NAMA MAHASISWA_123456.NAMA%TYPE;
    V_JURUSAN MAHASISWA_123456.JURUSAN%TYPE;
BEGIN
    SELECT NPM, NAMA, JURUSAN INTO V_NPM, V_NAMA, V_JURUSAN
    FROM MAHASISWA_123456
    WHERE NPM = V_NPM;
    DBMS_OUTPUT.PUT_LINE('NPM : ' || V_NPM);
    DBMS_OUTPUT.PUT_LINE('NAMA : ' || V_NAMA);
    DBMS_OUTPUT.PUT_LINE('JURUSAN : ' || V_JURUSAN);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Data Mahasiswa tidak ditemukan');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Program Error');
END;
/


-- NO 1 LEPKOM

DECLARE
    COME EMP.COMM%TYPE;
BEGIN
    SELECT COMM INTO COME FROM EMP
    WHER ENAME = 'EMP';
DBMS.OUTPUT.PUT_LINE('come : ' || COME);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS.OUTPUT.PUT_LINE('Data not found');
END;
/

-- NO 2 LEPKOM

DECLARE
    NAME VARCHAR2(100);
    SALARY NUMBER;
    BEGIN
    SELECT ENAME, SAL, INTO NAME, SALARY FROM EMP
    WHERE EMPNO = '7788';
IF SALARY > 4500 THEN
RAISE_APPLICATION_ERROR(-20001, 'Salary is too high');
END IF;
DBMS.OUTPUT.PUT_LINE('Name : ' || salary);
end;
/

-- NO 2 ACT
SET SERVEROUTPUT ON
DECLARE
    V_TABLE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TABLE FROM USER_TABLES;
    IF V_TABLE < 150 THEN
        RAISE_APPLICATION_ERROR(-20500, 'Tabel kurang, minimal 200 tabel');
    ELSE
        NULL;
    END IF;
END;
/